export const S = {
  app: {
    background: "#080808",
    color: "#EFEFEF",
    minHeight: "100vh",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize: 13,
  },
  header: {
    background: "#111",
    borderBottom: "1px solid #222",
    padding: "20px 20px 16px",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  h1: {
    fontFamily: "'Arial Black', 'Impact', sans-serif",
    fontSize: 28,
    fontWeight: 900,
    textTransform: "uppercase",
    letterSpacing: -0.5,
    lineHeight: 1,
    color: "#EFEFEF",
    margin: 0,
  },
  accent: { color: "#E8FF47" },
  sub: { fontSize: 11, color: "#555", textTransform: "uppercase", letterSpacing: "0.07em", marginTop: 4 },
  statsRow: { display: "flex", gap: 8, flexWrap: "wrap", marginTop: 14 },
  statBox: {
    background: "#1A1A1A",
    border: "1px solid #222",
    borderRadius: 6,
    padding: "8px 12px",
    textAlign: "center",
    minWidth: 60,
    flex: "1 1 60px",
  },
  statVal: { fontFamily: "'Arial Black', sans-serif", fontSize: 18, fontWeight: 900, color: "#E8FF47", lineHeight: 1 },
  statLabel: { fontSize: 9, color: "#444", textTransform: "uppercase", letterSpacing: "0.07em", marginTop: 2 },
  nav: {
    display: "flex",
    gap: 0,
    borderBottom: "1px solid #1A1A1A",
    background: "#0D0D0D",
    overflowX: "auto",
    position: "sticky",
    top: 0,
    zIndex: 99,
    WebkitOverflowScrolling: "touch",
  },
  navBtn: (active) => ({
    padding: "13px 16px",
    background: "none",
    border: "none",
    borderBottom: active ? "2px solid #E8FF47" : "2px solid transparent",
    color: active ? "#E8FF47" : "#444",
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.09em",
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "color 0.15s",
    flexShrink: 0,
  }),
  main: { padding: "16px", maxWidth: 860, margin: "0 auto", paddingBottom: 80 },
  card: {
    background: "#141414",
    border: "1px solid #1E1E1E",
    borderRadius: 8,
    padding: 14,
    marginBottom: 10,
  },
  cardTitle: {
    fontFamily: "'Arial Black', sans-serif",
    fontSize: 12,
    fontWeight: 900,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: 10,
  },
  pill: (color) => ({
    display: "inline-block",
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    padding: "3px 7px",
    borderRadius: 3,
    background: color + "18",
    color,
    border: `1px solid ${color}30`,
    marginRight: 5,
    marginBottom: 4,
  }),
  input: {
    background: "#1A1A1A",
    border: "1px solid #2A2A2A",
    borderRadius: 6,
    color: "#EFEFEF",
    padding: "10px 12px",
    fontSize: 13,
    width: "100%",
    outline: "none",
    marginBottom: 8,
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  textarea: {
    background: "#1A1A1A",
    border: "1px solid #2A2A2A",
    borderRadius: 6,
    color: "#EFEFEF",
    padding: "10px 12px",
    fontSize: 13,
    width: "100%",
    outline: "none",
    marginBottom: 8,
    resize: "vertical",
    minHeight: 80,
    boxSizing: "border-box",
    fontFamily: "inherit",
    lineHeight: 1.5,
  },
  btn: (color = "#E8FF47") => ({
    background: color,
    color: color === "#E8FF47" ? "#000" : "#fff",
    border: "none",
    borderRadius: 6,
    padding: "10px 16px",
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.09em",
    cursor: "pointer",
    marginRight: 8,
    marginTop: 4,
    fontFamily: "inherit",
  }),
  btnOutline: {
    background: "none",
    color: "#E8FF47",
    border: "1px solid #E8FF4730",
    borderRadius: 6,
    padding: "10px 16px",
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.09em",
    cursor: "pointer",
    marginRight: 8,
    marginTop: 4,
    fontFamily: "inherit",
  },
  weekCard: (active, phase) => {
    const c = phase === "build" ? "#4AACFF" : phase === "peak" ? "#E8FF47" : "#FF9A3C";
    return {
      background: active ? "#1A1A1A" : "#111",
      border: `1px solid ${active ? c + "33" : "#1A1A1A"}`,
      borderTop: `2px solid ${active ? c : "#1E1E1E"}`,
      borderRadius: 8,
      padding: 14,
      marginBottom: 8,
      cursor: "pointer",
      transition: "all 0.15s",
    };
  },
  chatBubble: (role) => ({
    background: role === "user" ? "#152015" : "#101520",
    border: `1px solid ${role === "user" ? "#3DFFA015" : "#4AACFF15"}`,
    borderRadius: role === "user" ? "12px 12px 3px 12px" : "12px 12px 12px 3px",
    padding: "12px 14px",
    marginBottom: 10,
    maxWidth: "90%",
    marginLeft: role === "user" ? "auto" : 0,
    fontSize: 13,
    lineHeight: 1.65,
    color: "#DEDEDE",
  }),
  label: {
    fontSize: 10,
    color: "#444",
    textTransform: "uppercase",
    letterSpacing: "0.07em",
    marginBottom: 4,
    display: "block",
    marginTop: 10,
  },
  flag: {
    background: "#1A0A0A",
    border: "1px solid #FF444430",
    borderLeft: "3px solid #FF5252",
    borderRadius: 6,
    padding: "10px 14px",
    marginBottom: 10,
    fontSize: 12,
    color: "#FF8080",
    lineHeight: 1.6,
  },
  sliderRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 4 },
  slider: { flex: 1, accentColor: "#E8FF47", cursor: "pointer" },
  sliderVal: {
    fontFamily: "'Arial Black', sans-serif",
    fontSize: 15,
    color: "#E8FF47",
    minWidth: 52,
    textAlign: "right",
  },
  mealBlock: (color) => ({
    background: color + "0D",
    borderLeft: `2px solid ${color}`,
    borderRadius: 3,
    padding: "8px 10px",
    marginBottom: 6,
    fontSize: 12,
    color: "#999",
    lineHeight: 1.55,
  }),
  mealLabel: (color) => ({
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color,
    marginBottom: 3,
    display: "block",
  }),
  quoteBlock: {
    background: "#0E0E08",
    border: "1px solid #E8FF4718",
    borderLeft: "3px solid #E8FF47",
    borderRadius: 5,
    padding: "12px 14px",
    marginBottom: 12,
  },
  dayGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 6,
    marginBottom: 14,
  },
  dayTile: (active, color) => ({
    background: active ? "#1A1A1A" : "#0E0E0E",
    border: `1px solid ${active ? color + "44" : "#151515"}`,
    borderRadius: 6,
    padding: "9px 4px",
    textAlign: "center",
    cursor: "pointer",
    transition: "all 0.15s",
  }),
};

export const typeColor = (t) => ({
  recovery: "#4AACFF",
  hard: "#E8FF47",
  rest: "#3DFFA0",
  tempo: "#4AACFF",
  long: "#FF9A3C"
}[t] || "#666");

export const phaseColor = (p) =>
  p === "build" ? "#4AACFF" : p === "peak" ? "#E8FF47" : "#FF9A3C";
